const $=s=>document.querySelector(s),E="errors135",S="stats135",P="progress135",T="testerNotice121";
const MODULES=["11.2.3.1","11.2.3.2","11.2.3.3","11.2.3.4","11.2.3.5","Rechtsgrundlagen","Anlage 1-A / 4-C"];
let Q=[],C=[],i=0,score=0,mode="learn",activeModule="";
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const ge=()=>load(E,[]),se=x=>save(E,[...new Set(x)]),gs=()=>load(S,{runs:0,best:0,last:0,examByModule:{}}),ss=x=>save(S,x),gp=()=>load(P,{}),sp=x=>save(P,x),qb=id=>Q.find(q=>q.id===id),sh=a=>[...a].sort(()=>Math.random()-.5);
const ACCESS="lskpAccess130",DAY=86400000,TRIAL_DAYS=14;
const CODE_HASHES={"2edafb98e501c5db228a2f1275b23d976f9ad6309c552dd771ad99596aa568ff":"admin","037889057abb898bf26bfa08cc3004e0950129b61c493d550f865407727e4ce3":"tester","d85d0c473ba6ac3adefa65a1f9b2e50b951347849f6770357f5a30dad23a536a":"tester","2e52587ff66205cb5736318951d7b7483c81dbeebd7c9838adb17017238061b9":"tester","9b6695acd5f6300f8676026cfea53c878ca458402cdf4f7aab64ad24f8e32bff":"tester"};
async function sha256(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s.trim().toUpperCase()));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
// Einmalige Migration auf Version 1.5.1: Lern- und Testergebnisse neu beginnen.
// Vorhandene Testzugänge erhalten ab dem ersten Start dieses Updates 14 neue Tage.
const RESET_VERSION="lskpReset151";
function migrate151(){
  if(localStorage.getItem(RESET_VERSION)==="1")return;
  [E,S,P].forEach(k=>localStorage.removeItem(k));
  const a=load(ACCESS,null);
  if(a&&a.role!=="admin"){const now=Date.now();a.activated=now;a.expires=now+TRIAL_DAYS*DAY;save(ACCESS,a)}
  localStorage.setItem(RESET_VERSION,"1");
}
migrate151();
function accessState(){return load(ACCESS,null)}
function accessValid(){let a=accessState();if(!a)return false;if(a.role==="admin")return true;return Date.now()<a.expires}
function daysLeft(){let a=accessState();if(!a||a.role==="admin")return null;return Math.max(0,Math.ceil((a.expires-Date.now())/DAY))}
function gate(msg=""){R(`<section class="accessgate"><div class="accessbox"><img class="gateicon" src="icon.png"><h1>LSKP TRAINER</h1><p class="gatesub">14-Tage-Testversion</p>${msg?`<div class="gateerror">${msg}</div>`:""}<p>Gib deinen persönlichen Freigabecode ein. Der 14-Tage-Zeitraum beginnt mit der ersten Aktivierung auf diesem Gerät.</p><input id="accessCode" class="codeinput" autocomplete="off" autocapitalize="characters" placeholder="Persönlicher Freigabecode"><button class="primary" onclick="activateAccess()">TESTZUGANG AKTIVIEREN</button><a class="request-access" href="mailto:svenwillumeit@gmx.de?subject=LSKP%20Trainer%20%E2%80%93%20Testzugang%20anfragen&body=Hallo%20Sven%2C%0A%0Aich%20m%C3%B6chte%20einen%20pers%C3%B6nlichen%20Testzugang%20zum%20LSKP-Trainer%20anfragen.%0A%0AName%3A%0A%0AViele%20Gr%C3%BC%C3%9Fe">✉ TESTZUGANG ANFRAGEN</a><p class="request-hint">Öffnet deine E-Mail-App. Der Freigabecode wird von Sven persönlich vergeben.</p><small class="gatenote">Adminzugang: ohne Zeitbegrenzung · Testzugang: 14 Tage</small><footer>© 2026 Sven Willumeit – Alle Rechte vorbehalten</footer></div></section>`)}
async function activateAccess(){let el=$("#accessCode"),code=(el?.value||"").trim().toUpperCase();if(!code)return gate("Bitte Freigabecode eingeben.");let h=await sha256(code),role=CODE_HASHES[h];if(!role)return gate("Freigabecode nicht gültig.");let now=Date.now(),a={role,activated:now,expires:role==="admin"?null:now+TRIAL_DAYS*DAY};save(ACCESS,a);home();testerNotice()}
function ensureAccess(){let a=accessState();if(!a)return gate();if(a.role!=="admin"&&Date.now()>=a.expires)return expired();home();testerNotice()}
function expired(){R(`<section class="accessgate"><div class="accessbox"><img class="gateicon" src="icon.png"><h1>Testzeitraum beendet</h1><p>Dein 14-Tage-Testzugang zum LSKP Trainer ist abgelaufen.</p><p class="muted">Vielen Dank fürs Testen und für dein Feedback.</p><a class="linkbtn" href="mailto:svenwillumeit@gmx.de?subject=LSKP%20Trainer%20-%20Testzugang">Sven Willumeit kontaktieren</a><footer>© 2026 Sven Willumeit – Alle Rechte vorbehalten</footer></div></section>`)}
fetch("questions.json").then(r=>r.json()).then(q=>{Q=q;ensureAccess()});
function R(h){$("#app").innerHTML=h;scrollTo(0,0)} function B(){return'<button class="back" onclick="home()">← Start</button>'}
function home(){let e=ge().filter(qb);se(e);R(`<section class="newhome redesign v153"><header class="rd-header"><button class="rd-menu-toggle" onclick="openSideMenu()" aria-label="Menü öffnen">☰</button><span>LSKP TRAINER</span><button class="rd-info" onclick="info()" aria-label="Informationen">ⓘ</button></header><div class="v153-hero"><div class="v153-skyline" aria-hidden="true"><span class="v153-tower"></span><span class="v153-terminal"></span><span class="v153-plane">✈</span></div><img class="v153-logo" src="icon.png" alt="LSKP Trainer Logo"><h1>LSKP <span>TRAINER</span></h1><p>LERNEN. ÜBEN. SICHER ANWENDEN.</p><small>FÜR DIE PRAXIS · FÜR DIE PRÜFUNG</small></div><div class="v153-grid"><button onclick="openNewLessons()"><span class="v153-symbol">▤</span><span><b>LERNEN</b><small>Wissen Schritt für Schritt aufbauen</small></span><i>›</i></button><button onclick="pick('exam')"><span class="v153-symbol">▣</span><span><b>PRÜFUNGSTRAINING</b><small>10, 20 oder 30 Fragen je Modul</small></span><i>›</i></button><button onclick="errors()"><span class="v153-symbol v153-error">✕</span><span><b>MEINE FEHLER</b><small>Gezielt wiederholen</small></span><i>›</i></button><button onclick="stats()"><span class="v153-symbol">▥</span><span><b>STATISTIK</b><small>Deinen Fortschritt ansehen</small></span><i>›</i></button><button onclick="laws()"><span class="v153-symbol">§</span><span><b>RECHTSGRUNDLAGEN</b><small>Öffentliche Vorschriften</small></span><i>›</i></button><button onclick="mods()"><span class="v153-symbol">☷</span><span><b>MODULE</b><small>11.2.3.1 – 11.2.3.5</small></span><i>›</i></button></div><div class="v153-extra"><button onclick="pick('learn')">Fragenkatalog · ${Q.length} Fragen</button><button onclick="startSimulation()">Prüfungssimulation · 30 Fragen</button></div><div class="v153-footer"><strong>SICHERHEIT BEGINNT MIT WISSEN.</strong><p>Private Testversion 1.5.3 · Lern- und Übungshilfe · keine offiziellen Prüfungsfragen</p><button onclick="refreshTrainer()">↻ APP AKTUALISIEREN</button><small>© 2026 Sven Willumeit · Alle Rechte vorbehalten</small></div></section>`)}
function openSideMenu(){document.body.insertAdjacentHTML('beforeend',`<div class="rd-overlay" id="rdOverlay" onclick="closeSideMenu()"><aside class="rd-drawer" onclick="event.stopPropagation()"><div class="rd-drawer-head"><b>LSKP TRAINER</b><button onclick="closeSideMenu()" aria-label="Menü schließen">✕</button></div><button onclick="closeSideMenu();home()">Startseite</button><button onclick="closeSideMenu();pick('learn')">Fragenkatalog</button><button onclick="closeSideMenu();pick('exam')">Übungstests</button><button onclick="closeSideMenu();startSimulation()">Prüfungssimulation</button><button onclick="closeSideMenu();stats()">Statistik</button><hr><button onclick="closeSideMenu();openNewLessons()">Lernkapitel: Grundlagen / GPA / Lieferungen</button><button onclick="closeSideMenu();errors()">Meine Fehler</button><button onclick="closeSideMenu();laws()">Rechtsgrundlagen</button><button onclick="closeSideMenu();mods()">Module 11.2.3.1–11.2.3.5</button><hr><button onclick="closeSideMenu();info()">Lernhinweise, Datenschutz & Impressum</button><button onclick="closeSideMenu();refreshTrainer()">App aktualisieren</button><small>© 2026 Sven Willumeit</small></aside></div>`)}
function closeSideMenu(){document.getElementById('rdOverlay')?.remove()}
function startSimulation(){
  mode='exam';activeModule='Prüfungssimulation';
  // Round-robin across all available learning areas; 30 distinct questions.
  const groups=MODULES.map(m=>sh(Q.filter(q=>q.module===m))).filter(g=>g.length);
  const selected=[];
  while(selected.length<30 && groups.some(g=>g.length)){
    for(const group of sh(groups)){
      if(selected.length>=30)break;
      if(group.length)selected.push(group.pop());
    }
  }
  C=sh(selected);i=0;score=0;show();
}

function testerNotice(){if(localStorage.getItem(T))return;document.body.insertAdjacentHTML("beforeend",`<div class="modalshade" id="testerNotice"><div class="modal"><div class="modaltag">BETA-TESTVERSION</div><h2>Hinweis zur Testversion</h2><p>Diese Testversion des <b>LSKP Trainers</b> ist ausschließlich für die von Sven Willumeit persönlich ausgewählten Testpersonen bestimmt.</p><p><b>Eine Weitergabe des Zugangs, Links, der Anwendung, von Kopien oder Dateien an Dritte ist ohne vorherige ausdrückliche Zustimmung von Sven Willumeit nicht gestattet.</b></p><p>Die Bereitstellung zu Testzwecken überträgt keine Nutzungs- oder Verwertungsrechte.</p><p><b>© 2026 Sven Willumeit – Alle Rechte vorbehalten.</b></p><button class="primary" onclick="acceptTesterNotice()">Hinweis gelesen – Test starten</button></div></div>`)}
function acceptTesterNotice(){localStorage.setItem(T,"1");document.getElementById("testerNotice")?.remove()} function registerSoon(){alert("Diese Testversion wird über einen persönlichen Freigabecode aktiviert.")}
function pick(m){mode=m;R(B()+`<h2>${m==='learn'?'📚 Lernen':'📝 Prüfungstraining'}</h2><p class="muted">${m==='learn'?'Wähle einen Lernbereich. Dein Fortschritt wird auf diesem Gerät gespeichert.':'Wähle einen Bereich. Du kannst 10, 20 oder 30 Fragen üben.'}</p><div class="stack">`+MODULES.map(x=>`<button class="wide" onclick="start('${x.replaceAll("'","\\'")}')"><b>${x}</b><small>${Q.filter(q=>q.module===x).length} Übungsfragen${m==='learn'?` · ${learnPct(x)}% gelernt`:''}</small></button>`).join("")+"</div>")}
function start(m){activeModule=m;C=sh(Q.filter(q=>q.module===m));if(mode==='exam'){R(B()+`<h2>Wie viele Fragen möchtest du üben?</h2><p class="muted">Modul ${m} · ${C.length} Fragen verfügbar</p><div class="stack">${[10,20,30].map(n=>`<button class="wide" onclick="startWithCount(${n})">${n} Fragen</button>`).join('')}</div>`);return}i=0;score=0;show()}
function startWithCount(n){C=C.slice(0,Math.min(n,C.length));i=0;score=0;show()}
function show(){if(i>=C.length)return finish();let q=C[i],multi=Array.isArray(q.correct),count=multi?q.correct.length:1;R(B()+`<div class="progress">${mode==='learn'?'Lernen':'Prüfung'} · Frage ${i+1} von ${C.length}</div><h2>${q.module}</h2><div class="card"><h3>${q.question}</h3><p class="muted">${multi?`Mehrfachauswahl · ${count} richtige Antworten`:'Eine Antwort ist richtig'}</p><div class="answers">${multi?q.answers.map((a,n)=>`<label class="multi-answer"><input type="checkbox" class="multi-choice" value="${n}"><span>${a}</span></label>`).join('')+`<button class="primary" onclick="submitMulti()">Antworten prüfen</button>`:q.answers.map((a,n)=>`<button onclick="ans(${n})">${a}</button>`).join('')}</div></div>`)}
function submitMulti(){let q=C[i];let selected=[...document.querySelectorAll('.multi-choice:checked')].map(el=>Number(el.value));if(selected.length!==q.correct.length){alert(`Bitte genau ${q.correct.length} Antworten auswählen.`);return}recordAnswer(selected)}
function ans(n){recordAnswer([n])}
function recordAnswer(selected){let q=C[i],correct=Array.isArray(q.correct)?q.correct:[q.correct],ok=selected.length===correct.length&&selected.every(n=>correct.includes(n));if(!ok){let e=ge();if(!e.includes(q.id)){e.push(q.id);se(e)}}else if(mode==='errors')se(ge().filter(x=>x!==q.id));if(ok)score++;if(mode==='learn'){let p=gp();p[q.module]=[...new Set([...(p[q.module]||[]),q.id])];sp(p)}if(mode==='exam'){i++;return show()}R(B()+`<div class="card"><h2>${ok?'✅ Richtig':'❌ Nicht richtig'}</h2><p><b>Richtige Antwort${correct.length>1?'en':''}:</b></p><ul>${correct.map(n=>`<li>${q.answers[n]}</li>`).join('')}</ul><p>${q.explanation}</p><p class="muted">Bezug: ${q.legal}</p><button class="primary" onclick="i++;show()">Weiter</button></div>`)}
function finish(){let pct=C.length?Math.round(score/C.length*100):0;if(mode==='exam'){let s=gs();s.runs++;s.last=pct;s.best=Math.max(s.best,pct);s.examByModule[activeModule]={last:pct,best:Math.max(s.examByModule[activeModule]?.best||0,pct)};ss(s)}R(B()+`<div class="card"><h2>${mode==='learn'?'Lernrunde':'Prüfungsrunde'} beendet</h2><div class="big">${score}/${C.length}</div><p>${pct}% richtig</p>${mode==='learn'?`<p><b>Lernfortschritt ${activeModule}: ${learnPct(activeModule)}%</b></p>`:''}<button class="primary" onclick="home()">Zur Startseite</button></div>`)}
function errors(){C=sh(ge().map(qb).filter(Boolean));i=0;score=0;mode='errors';activeModule='Meine Fehler';if(!C.length)return R(B()+'<div class="card"><h2>🎉 Keine gespeicherten Fehler</h2><p>Aktuell ist deine Fehlerliste leer.</p></div>');show()}
function learnPct(m){let total=Q.filter(q=>q.module===m).length,done=(gp()[m]||[]).filter(id=>Q.some(q=>q.id===id&&q.module===m)).length;return total?Math.round(done/total*100):0}
function overallLearnPct(){let total=Q.length,done=MODULES.reduce((n,m)=>n+(gp()[m]||[]).filter(id=>Q.some(q=>q.id===id&&q.module===m)).length,0);return total?Math.round(done/total*100):0}
function donut(p,label,sub){return `<div class="statitem"><div class="donut" style="--p:${p}"><span>${p}%</span></div><b>${label}</b><small>${sub}</small></div>`}
function stats(){let s=gs(),e=ge().filter(qb).length,lp=overallLearnPct();R(B()+`<h2>📊 Auswertung</h2><div class="card summarycard"><h3>Gesamtübersicht</h3><div class="examstats">${donut(lp,'Lernen',`${MODULES.reduce((n,m)=>n+(gp()[m]||[]).filter(id=>Q.some(q=>q.id===id&&q.module===m)).length,0)}/${Q.length} Fragen bearbeitet`)}${donut(s.last||0,'Prüfungstraining',s.runs?`Letzter Test · Bestwert ${s.best}%`:'Noch kein Test absolviert')}</div></div><div class="card"><h3>Lernen · Bereiche</h3><div class="moduleprogress">${MODULES.map(m=>{let d=(gp()[m]||[]).filter(id=>Q.some(q=>q.id===id&&q.module===m)).length,p=learnPct(m);return `<div class="progressrow"><div><b>${m}</b><small>${d}/${Q.filter(q=>q.module===m).length} gelernt</small></div><div class="progressbar"><span style="width:${p}%"></span></div><strong>${p}%</strong></div>`}).join('')}</div></div><div class="card"><h3>Prüfungstraining</h3><div class="quickstats"><div><b>${s.runs}</b><small>Tests</small></div><div><b>${s.last||0}%</b><small>Letzter Test</small></div><div><b>${s.best||0}%</b><small>Bestwert</small></div><div><b>${e}</b><small>Fehler gespeichert</small></div></div><p class="muted">Persönliche Lernstatistik – keine Aussage über ein amtliches Prüfungsergebnis.</p></div>`) }
function laws(){let L=[["VO (EG) Nr. 300/2008","Gemeinsame Grundvorschriften für die Sicherheit in der Zivilluftfahrt.","https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32008R0300"],["VO (EU) Nr. 272/2009","Ergänzt die gemeinsamen Grundstandards.","https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32009R0272"],["DVO (EU) 2015/1998","Detaillierte Maßnahmen; u. a. Anlagen 1-A und 4-C.","https://eur-lex.europa.eu/eli/reg_impl/2015/1998/oj/deu"],["LuftSiG","Nationales Luftsicherheitsgesetz; u. a. § 11 verbotene Gegenstände.","https://www.gesetze-im-internet.de/luftsig/"],["LuftSiSchulV","Schulung im Bereich Luftsicherheit.","https://www.gesetze-im-internet.de/luftsischulv_2023/"]];R(B()+`<h2>⚖️ Rechtsgrundlagen</h2><div class="card"><button class="primary" onclick="mode='learn';start('Rechtsgrundlagen')">Rechtsfragen lernen</button></div>`+L.map(x=>`<div class="card"><h3>${x[0]}</h3><p>${x[1]}</p><a class="linkbtn" target="_blank" rel="noopener" href="${x[2]}">Amtliche Fassung öffnen ↗</a></div>`).join('')+'<div class="notice">Maßgeblich ist immer die aktuell geltende amtliche Fassung. Keine Rechtsberatung.</div>')}
function mods(){let n={"11.2.3.1":"Personen und mitgeführte Gegenstände","11.2.3.2":"Fracht & Post","11.2.3.3":"Flughafenlieferungen & Bordvorräte","11.2.3.4":"Fahrzeugkontrollen","11.2.3.5":"Zugangskontrollen & Streifengänge","Rechtsgrundlagen":"EU- und nationale Rechtsgrundlagen","Anlage 1-A / 4-C":"Verbotene Gegenstände"};R(B()+"<h2>✈️ Lernbereiche</h2>"+Object.entries(n).map(([m,x])=>`<div class="card"><h3>${m}</h3><p>${x}</p><p class="muted">${Q.filter(q=>q.module===m).length} Übungsfragen · ${learnPct(m)}% gelernt</p></div>`).join(''))}
function info(){let su=encodeURIComponent('Feedback zum LSKP Trainer – Testversion 1.5.3'),bo=encodeURIComponent('Name (optional):\n\nGetesteter Bereich:\n\nWas funktioniert gut?\n\nWas sollte verbessert werden?\n\nFehler / Auffälligkeit:\n\nWeitere Wünsche:\n');R(B()+`<h2>ℹ️ Info & Rechtliches</h2><div class="card"><h3>LSKP Trainer – Testversion 1.5.3</h3><p>Unabhängige private Lern- und Übungshilfe mit ${Q.length} selbst erstellten Übungsfragen. Keine offiziellen oder aktuellen Prüfungsfragen.</p><p>Ersetzt keine vorgeschriebene Schulung, behördliche Prüfung oder betriebliche Anweisung.</p></div><div class="card"><h3>👤 Registrierung</h3><p>Die Testversion wird über einen persönlichen Freigabecode aktiviert. Es werden keine Registrierungsdaten erhoben; der Testzeitraum wird nur auf diesem Gerät gespeichert.</p><button class="registerbtn" onclick="registerSoon()">REGISTRIEREN <small>Demnächst verfügbar</small></button></div><div class="card"><h3>🔒 Testversion</h3><p>Nur für persönlich ausgewählte Testpersonen. Keine Weitergabe ohne vorherige ausdrückliche Zustimmung von Sven Willumeit.</p><p><b>© 2026 Sven Willumeit – Alle Rechte vorbehalten.</b></p></div><div class="card"><h3>💬 Feedback</h3><a class="linkbtn" href="mailto:svenwillumeit@gmx.de?subject=${su}&body=${bo}">Feedback senden</a></div><div class="card"><h3>Kontakt</h3><p><a href="mailto:svenwillumeit@gmx.de">svenwillumeit@gmx.de</a></p></div>`)}

async function refreshTrainer(){try{if("serviceWorker" in navigator){const r=await navigator.serviceWorker.getRegistration();if(r)await r.update();}if("caches" in window){const ks=await caches.keys();await Promise.all(ks.filter(k=>k.startsWith("lskp-")).map(k=>caches.delete(k)));}location.reload();}catch(e){alert("Aktualisierung fehlgeschlagen. Bitte Internetverbindung prüfen.");}}
