const $=s=>document.querySelector(s),E="errors",S="stats121",P="progress121",T="testerNotice121";
const MODULES=["11.2.3.1","11.2.3.2","11.2.3.3","11.2.3.4","11.2.3.5","Rechtsgrundlagen","Anlage 1-A / 4-C"];
let Q=[],C=[],i=0,score=0,mode="learn",activeModule="";
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const ge=()=>load(E,[]),se=x=>save(E,[...new Set(x)]),gs=()=>load(S,{runs:0,best:0,last:0,examByModule:{}}),ss=x=>save(S,x),gp=()=>load(P,{}),sp=x=>save(P,x),qb=id=>Q.find(q=>q.id===id),sh=a=>[...a].sort(()=>Math.random()-.5);
const ACCESS="lskpAccess130",DAY=86400000,TRIAL_DAYS=7;
const CODE_HASHES={"2edafb98e501c5db228a2f1275b23d976f9ad6309c552dd771ad99596aa568ff":"admin","037889057abb898bf26bfa08cc3004e0950129b61c493d550f865407727e4ce3":"tester","d85d0c473ba6ac3adefa65a1f9b2e50b951347849f6770357f5a30dad23a536a":"tester","2e52587ff66205cb5736318951d7b7483c81dbeebd7c9838adb17017238061b9":"tester","9b6695acd5f6300f8676026cfea53c878ca458402cdf4f7aab64ad24f8e32bff":"tester"};
async function sha256(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s.trim().toUpperCase()));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function accessState(){return load(ACCESS,null)}
function accessValid(){let a=accessState();if(!a)return false;if(a.role==="admin")return true;return Date.now()<a.expires}
function daysLeft(){let a=accessState();if(!a||a.role==="admin")return null;return Math.max(0,Math.ceil((a.expires-Date.now())/DAY))}
function gate(msg=""){R(`<section class="accessgate"><div class="accessbox"><img class="gateicon" src="icon.png"><h1>LSKP TRAINER</h1><p class="gatesub">7-Tage-Testversion</p>${msg?`<div class="gateerror">${msg}</div>`:""}<p>Gib deinen persönlichen Freigabecode ein. Der 7-Tage-Zeitraum beginnt mit der ersten Aktivierung auf diesem Gerät.</p><input id="accessCode" class="codeinput" autocomplete="off" autocapitalize="characters" placeholder="Persönlicher Freigabecode"><button class="primary" onclick="activateAccess()">TESTZUGANG AKTIVIEREN</button><small class="gatenote">Adminzugang: ohne Zeitbegrenzung · Testzugang: 7 Tage</small><footer>© 2026 Sven Willumeit – Alle Rechte vorbehalten</footer></div></section>`)}
async function activateAccess(){let el=$("#accessCode"),code=(el?.value||"").trim().toUpperCase();if(!code)return gate("Bitte Freigabecode eingeben.");let h=await sha256(code),role=CODE_HASHES[h];if(!role)return gate("Freigabecode nicht gültig.");let now=Date.now(),a={role,activated:now,expires:role==="admin"?null:now+TRIAL_DAYS*DAY};save(ACCESS,a);home();testerNotice()}
function ensureAccess(){let a=accessState();if(!a)return gate();if(a.role!=="admin"&&Date.now()>=a.expires)return expired();home();testerNotice()}
function expired(){R(`<section class="accessgate"><div class="accessbox"><img class="gateicon" src="icon.png"><h1>Testzeitraum beendet</h1><p>Dein 7-Tage-Testzugang zum LSKP Trainer ist abgelaufen.</p><p class="muted">Vielen Dank fürs Testen und für dein Feedback.</p><a class="linkbtn" href="mailto:svenwillumeit@gmx.de?subject=LSKP%20Trainer%20-%20Testzugang">Sven Willumeit kontaktieren</a><footer>© 2026 Sven Willumeit – Alle Rechte vorbehalten</footer></div></section>`)}
fetch("questions.json").then(r=>r.json()).then(q=>{Q=q;ensureAccess()});
function R(h){$("#app").innerHTML=h;scrollTo(0,0)} function B(){return'<button class="back" onclick="home()">← Start</button>'}
function home(){let e=ge().filter(qb);se(e);let s=gs();R(`<section class="newhome"><div class="topbar"><div class="brand"><img class="shieldlogo" src="icon.png"><div><h1>LSKP TRAINER</h1><p>Lernen. Üben. Sicher anwenden.</p></div></div><div class="topactions"><button onclick="registerSoon()">👤<small>Registrieren</small></button><button onclick="info()">ⓘ<small>Info</small></button></div></div><div class="airportHero compactHero"><p>LERNEN. ÜBEN. SICHER ANWENDEN.</p><small>FÜR DIE PRAXIS. FÜR DIE PRÜFUNG. FÜR MEHR SICHERHEIT.</small></div><div class="notice"><b>Testversion 1.3.1</b> · 210 selbst erstellte Übungsfragen · keine offiziellen Prüfungsfragen</div><div class="accessstatus">${accessState()?.role==='admin'?'🔐 Adminzugang · unbegrenzt':`🟢 Testzugang aktiv · noch ${daysLeft()} Tag${daysLeft()===1?'':'e'}`}</div><div class="card"><button class="primary" style="background:#16834a;width:100%;font-weight:800" onclick="refreshTrainer()">🔄 APP AKTUALISIEREN</button><small>Neue Version laden · Lernstand und Testzugang bleiben gespeichert</small></div><div class="card newmoduleentry"><h3>🆕 Neue Lernkapitel</h3><p>Auftrag und Ziel · GPA – Grundlagen und Bilddarstellung</p><button class="primary" onclick="openNewLessons()">LERNKAPITEL ÖFFNEN</button></div><div class="featuregrid"><button class="feature" onclick="pick('learn')"><span>📚</span><div><b>LERNEN</b><small>7 Lernbereiche · 210 Fragen</small></div><i>›</i></button><button class="feature" onclick="pick('exam')"><span>📝</span><div><b>PRÜFUNGSTRAINING</b><small>Praxisnah üben – Wissen festigen</small></div><i>›</i></button><button class="feature" onclick="errors()"><span>❌</span><div><b>MEINE FEHLER</b><small>${e.length} gespeichert</small></div><i>›</i></button><button class="feature" onclick="stats()"><span>📊</span><div><b>AUSWERTUNG</b><small>Lernen + Prüfungstraining</small></div><i>›</i></button><button class="feature legalfeature" onclick="laws()"><span>§</span><div><b>RECHTSGRUNDLAGEN</b><small>Lernen + amtliche Quellen</small></div><i>›</i></button><button class="feature" onclick="mods()"><span>☰</span><div><b>MODULE</b><small>11.2.3.1 – 11.2.3.5 und mehr</small></div><i>›</i></button></div><div class="safetyline">✈︎ <b>SICHERHEIT BEGINNT MIT WISSEN.</b></div><footer>Private Testversion · Lern- und Übungshilfe · keine offiziellen Prüfungsfragen<br>© 2026 Sven Willumeit – Alle Rechte vorbehalten</footer><nav class="bottomnav"><button onclick="home()">⌂<small>Start</small></button><button onclick="pick('learn')">▤<small>Lernen</small></button><button onclick="stats()">▥<small>Statistik</small></button><button onclick="info()">•••<small>Mehr</small></button></nav></section>`)}
function testerNotice(){if(localStorage.getItem(T))return;document.body.insertAdjacentHTML("beforeend",`<div class="modalshade" id="testerNotice"><div class="modal"><div class="modaltag">BETA-TESTVERSION</div><h2>Hinweis zur Testversion</h2><p>Diese Testversion des <b>LSKP Trainers</b> ist ausschließlich für die von Sven Willumeit persönlich ausgewählten Testpersonen bestimmt.</p><p><b>Eine Weitergabe des Zugangs, Links, der Anwendung, von Kopien oder Dateien an Dritte ist ohne vorherige ausdrückliche Zustimmung von Sven Willumeit nicht gestattet.</b></p><p>Die Bereitstellung zu Testzwecken überträgt keine Nutzungs- oder Verwertungsrechte.</p><p><b>© 2026 Sven Willumeit – Alle Rechte vorbehalten.</b></p><button class="primary" onclick="acceptTesterNotice()">Hinweis gelesen – Test starten</button></div></div>`)}
function acceptTesterNotice(){localStorage.setItem(T,"1");document.getElementById("testerNotice")?.remove()} function registerSoon(){alert("Diese Testversion wird über einen persönlichen Freigabecode aktiviert.")}
function pick(m){mode=m;R(B()+`<h2>${m==='learn'?'📚 Lernen':'📝 Prüfungstraining'}</h2><p class="muted">${m==='learn'?'Wähle einen Lernbereich. Dein Fortschritt wird auf diesem Gerät gespeichert.':'Wähle einen Bereich für eine 10-Fragen-Testrunde.'}</p><div class="stack">`+MODULES.map(x=>`<button class="wide" onclick="start('${x.replaceAll("'","\\'")}')"><b>${x}</b><small>${Q.filter(q=>q.module===x).length} Übungsfragen${m==='learn'?` · ${learnPct(x)}% gelernt`:''}</small></button>`).join("")+"</div>")}
function start(m){activeModule=m;C=sh(Q.filter(q=>q.module===m));if(mode==='exam')C=C.slice(0,10);i=0;score=0;show()}
function show(){if(i>=C.length)return finish();let q=C[i];R(B()+`<div class="progress">${mode==='learn'?'Lernen':'Prüfung'} · Frage ${i+1} von ${C.length}</div><h2>${q.module}</h2><div class="card"><h3>${q.question}</h3><div class="answers">${q.answers.map((a,n)=>`<button onclick="ans(${n})">${a}</button>`).join("")}</div></div>`)}
function ans(n){let q=C[i],ok=n===q.correct;if(!ok){let e=ge();if(!e.includes(q.id)){e.push(q.id);se(e)}}else if(mode==='errors')se(ge().filter(x=>x!==q.id));if(ok)score++;if(mode==='learn'){let p=gp();p[q.module]=[...new Set([...(p[q.module]||[]),q.id])];sp(p)}if(mode==='exam'){i++;return show()}R(B()+`<div class="card"><h2>${ok?'✅ Richtig':'❌ Nicht richtig'}</h2><p><b>${q.answers[q.correct]}</b></p><p>${q.explanation}</p><p class="muted">Bezug: ${q.legal}</p><button class="primary" onclick="i++;show()">Weiter</button></div>`)}
function finish(){let pct=C.length?Math.round(score/C.length*100):0;if(mode==='exam'){let s=gs();s.runs++;s.last=pct;s.best=Math.max(s.best,pct);s.examByModule[activeModule]={last:pct,best:Math.max(s.examByModule[activeModule]?.best||0,pct)};ss(s)}R(B()+`<div class="card"><h2>${mode==='learn'?'Lernrunde':'Prüfungsrunde'} beendet</h2><div class="big">${score}/${C.length}</div><p>${pct}% richtig</p>${mode==='learn'?`<p><b>Lernfortschritt ${activeModule}: ${learnPct(activeModule)}%</b></p>`:''}<button class="primary" onclick="home()">Zur Startseite</button></div>`)}
function errors(){C=sh(ge().map(qb).filter(Boolean));i=0;score=0;mode='errors';activeModule='Meine Fehler';if(!C.length)return R(B()+'<div class="card"><h2>🎉 Keine gespeicherten Fehler</h2><p>Aktuell ist deine Fehlerliste leer.</p></div>');show()}
function learnPct(m){let total=Q.filter(q=>q.module===m).length,done=(gp()[m]||[]).filter(id=>Q.some(q=>q.id===id&&q.module===m)).length;return total?Math.round(done/total*100):0}
function overallLearnPct(){let total=Q.length,done=MODULES.reduce((n,m)=>n+(gp()[m]||[]).filter(id=>Q.some(q=>q.id===id&&q.module===m)).length,0);return total?Math.round(done/total*100):0}
function donut(p,label,sub){return `<div class="statitem"><div class="donut" style="--p:${p}"><span>${p}%</span></div><b>${label}</b><small>${sub}</small></div>`}
function stats(){let s=gs(),e=ge().filter(qb).length,lp=overallLearnPct();R(B()+`<h2>📊 Auswertung</h2><div class="card summarycard"><h3>Gesamtübersicht</h3><div class="examstats">${donut(lp,'Lernen',`${MODULES.reduce((n,m)=>n+(gp()[m]||[]).filter(id=>Q.some(q=>q.id===id&&q.module===m)).length,0)}/${Q.length} Fragen bearbeitet`)}${donut(s.last||0,'Prüfungstraining',s.runs?`Letzter Test · Bestwert ${s.best}%`:'Noch kein Test absolviert')}</div></div><div class="card"><h3>Lernen · Bereiche</h3><div class="moduleprogress">${MODULES.map(m=>{let d=(gp()[m]||[]).filter(id=>Q.some(q=>q.id===id&&q.module===m)).length,p=learnPct(m);return `<div class="progressrow"><div><b>${m}</b><small>${d}/30 gelernt</small></div><div class="progressbar"><span style="width:${p}%"></span></div><strong>${p}%</strong></div>`}).join('')}</div></div><div class="card"><h3>Prüfungstraining</h3><div class="quickstats"><div><b>${s.runs}</b><small>Tests</small></div><div><b>${s.last||0}%</b><small>Letzter Test</small></div><div><b>${s.best||0}%</b><small>Bestwert</small></div><div><b>${e}</b><small>Fehler gespeichert</small></div></div><p class="muted">Persönliche Lernstatistik – keine Aussage über ein amtliches Prüfungsergebnis.</p></div>`) }
function laws(){let L=[["VO (EG) Nr. 300/2008","Gemeinsame Grundvorschriften für die Sicherheit in der Zivilluftfahrt.","https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32008R0300"],["VO (EU) Nr. 272/2009","Ergänzt die gemeinsamen Grundstandards.","https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32009R0272"],["DVO (EU) 2015/1998","Detaillierte Maßnahmen; u. a. Anlagen 1-A und 4-C.","https://eur-lex.europa.eu/eli/reg_impl/2015/1998/oj/deu"],["LuftSiG","Nationales Luftsicherheitsgesetz; u. a. § 11 verbotene Gegenstände.","https://www.gesetze-im-internet.de/luftsig/"],["LuftSiSchulV","Schulung im Bereich Luftsicherheit.","https://www.gesetze-im-internet.de/luftsischulv_2023/"]];R(B()+`<h2>⚖️ Rechtsgrundlagen</h2><div class="card"><button class="primary" onclick="mode='learn';start('Rechtsgrundlagen')">30 Rechtsfragen lernen</button></div>`+L.map(x=>`<div class="card"><h3>${x[0]}</h3><p>${x[1]}</p><a class="linkbtn" target="_blank" rel="noopener" href="${x[2]}">Amtliche Fassung öffnen ↗</a></div>`).join('')+'<div class="notice">Maßgeblich ist immer die aktuell geltende amtliche Fassung. Keine Rechtsberatung.</div>')}
function mods(){let n={"11.2.3.1":"Personen und mitgeführte Gegenstände","11.2.3.2":"Fracht & Post","11.2.3.3":"Flughafenlieferungen & Bordvorräte","11.2.3.4":"Fahrzeugkontrollen","11.2.3.5":"Zugangskontrollen & Streifengänge","Rechtsgrundlagen":"EU- und nationale Rechtsgrundlagen","Anlage 1-A / 4-C":"Verbotene Gegenstände"};R(B()+"<h2>✈️ Lernbereiche</h2>"+Object.entries(n).map(([m,x])=>`<div class="card"><h3>${m}</h3><p>${x}</p><p class="muted">30 Übungsfragen · ${learnPct(m)}% gelernt</p></div>`).join(''))}
function info(){let su=encodeURIComponent('Feedback zum LSKP Trainer – Testversion 1.3.1'),bo=encodeURIComponent('Name (optional):\n\nGetesteter Bereich:\n\nWas funktioniert gut?\n\nWas sollte verbessert werden?\n\nFehler / Auffälligkeit:\n\nWeitere Wünsche:\n');R(B()+`<h2>ℹ️ Info & Rechtliches</h2><div class="card"><h3>LSKP Trainer – Testversion 1.3.1</h3><p>Unabhängige private Lern- und Übungshilfe mit 210 selbst erstellten Übungsfragen. Keine offiziellen oder aktuellen Prüfungsfragen.</p><p>Ersetzt keine vorgeschriebene Schulung, behördliche Prüfung oder betriebliche Anweisung.</p></div><div class="card"><h3>👤 Registrierung</h3><p>Die Testversion wird über einen persönlichen Freigabecode aktiviert. Es werden keine Registrierungsdaten erhoben; der Testzeitraum wird nur auf diesem Gerät gespeichert.</p><button class="registerbtn" onclick="registerSoon()">REGISTRIEREN <small>Demnächst verfügbar</small></button></div><div class="card"><h3>🔒 Testversion</h3><p>Nur für persönlich ausgewählte Testpersonen. Keine Weitergabe ohne vorherige ausdrückliche Zustimmung von Sven Willumeit.</p><p><b>© 2026 Sven Willumeit – Alle Rechte vorbehalten.</b></p></div><div class="card"><h3>💬 Feedback</h3><a class="linkbtn" href="mailto:svenwillumeit@gmx.de?subject=${su}&body=${bo}">Feedback senden</a></div><div class="card"><h3>Kontakt</h3><p><a href="mailto:svenwillumeit@gmx.de">svenwillumeit@gmx.de</a></p></div>`)}

async function refreshTrainer(){try{if("serviceWorker" in navigator){const r=await navigator.serviceWorker.getRegistration();if(r)await r.update();}if("caches" in window){const ks=await caches.keys();await Promise.all(ks.filter(k=>k.startsWith("lskp-")).map(k=>caches.delete(k)));}location.reload();}catch(e){alert("Aktualisierung fehlgeschlagen. Bitte Internetverbindung prüfen.");}}
