const LESSON_QUIZ=[{"q": "Was ist ein wesentliches Ziel der Luftsicherheitskontrolle?", "a": ["Nur Wartezeiten verringern", "Das Einbringen verbotener Gegenstände verhindern", "Alle Gegenstände automatisch freigeben"], "c": 1, "why": "Die Kontrollen dienen insbesondere dem Schutz vor verbotenen Gegenständen."}, {"q": "Welche Bereiche umfasst der Auftrag der Luftsicherheitskontrolle?", "a": ["Nur Handgepäck", "Personen und Gegenstände, Fahrzeuge sowie Waren und Versorgungsgüter", "Nur Fahrzeuge"], "c": 1, "why": "Der Kontrollauftrag umfasst mehrere Personengruppen und Güterarten."}, {"q": "Was ist der Unterschied zwischen Zutrittsberechtigung und Sicherheitskontrolle?", "a": ["Es ist dasselbe", "Eine Berechtigung ersetzt jede Kontrolle", "Es sind unterschiedliche Anforderungen"], "c": 2, "why": "Eine Zutrittsberechtigung allein ersetzt keine vorgeschriebene Kontrolle."}, {"q": "Wie entsteht vereinfacht das Bild einer GPA?", "a": ["Durch Röntgenstrahlung und Detektormessungen", "Durch ein gewöhnliches Foto", "Ausschließlich durch Gewichtsbestimmung"], "c": 0, "why": "Detektoren erfassen die durch das Objekt gelangende Strahlung."}, {"q": "Welche Bilddarstellung bezeichnet Hi-Cat?", "a": ["Eine Ausweisart", "Graustufen- und Konturendarstellung", "Eine ETD-Probe"], "c": 1, "why": "Hi-Cat bezeichnet eine Graustufen- und Konturendarstellung."}, {"q": "Was ist bei GPA-Auswertefunktionen zu beachten?", "a": ["Sie sind an jedem Gerät identisch", "Sie ersetzen sämtliche Kontrollen", "Bezeichnungen und Wirkungen sind geräteabhängig"], "c": 2, "why": "Die tatsächliche Bedienung richtet sich nach dem eingesetzten Gerät und den geltenden Anweisungen."}];
function openNewLessons(section='auftrag'){
 if(!accessValid())return ensureAccess();
 const selected=['auftrag','gpa','recht','begriffe','quiz'].includes(section)?section:'auftrag';
 const button=(id,label)=>`<button class="lesson-tab ${selected===id?'selected':''}" onclick="openNewLessons('${id}')">${label}</button>`;
 const nav=`${B()}<h2>📚 Neue Lernkapitel</h2><div class="lesson-tabs">${button('auftrag','Auftrag & Ziel')}${button('gpa','GPA')}${button('recht','EU-Recht & Säulen')}${button('begriffe','Abkürzungen')}${button('quiz','Wissenstest')}</div>`;
 const note='<div class="lesson-note"><b>Hinweis für die Testversion:</b> Unabhängige Lernhilfe. Maßgeblich sind die jeweils geltenden Rechtsvorschriften, Schulungsunterlagen und Gerätevorgaben; diese Lernhilfe ersetzt keine betriebliche Anweisung.</div>';
 let body='';
 if(selected==='auftrag')body=`<div class="card"><h3>1 · Auftrag und Ziel</h3><p><b>Auftrag:</b> Vor dem Zutritt, der Zufahrt oder dem Verbringen in sensible Teile der Sicherheitsbereiche sind die jeweils vorgeschriebenen Kontrollen durchzuführen. Dazu gehören Personen und mitgeführte Gegenstände, Fahrzeuge sowie Waren und Versorgungsgüter.</p><p><b>Ziel:</b> Unbefugten Zugang und das Einbringen verbotener Gegenstände verhindern. Zutrittsberechtigung und vorgeschriebene Sicherheitskontrolle sind unterschiedliche Voraussetzungen.</p><h3>Merksatz</h3><p>Wichtige Fundstellen sind die Anlagen <b>1-A</b> und <b>4-C</b> der Durchführungsverordnung (EU) 2015/1998. Vor praktischer Anwendung gilt stets die aktuelle Fassung.</p></div>`;
 if(selected==='gpa')body=`<div class="card"><h3>2 · GPA – Grundlagen</h3><p>Die <b>Gepäckprüfanlage (GPA)</b> erzeugt mithilfe von Röntgentechnik eine Darstellung der durchleuchteten Gegenstände. Ein Generator sendet Röntgenstrahlung durch das Objekt. Detektoren erfassen die ankommende Strahlung, aus deren Messwerten ein Bild entsteht.</p><div class="gpa-scheme"><div>Röntgenquelle</div><span>→</span><div>Gepäck auf Förderband</div><span>→</span><div>Detektoren</div></div><p class="muted">Vereinfachtes Prinzip, keine Bauanleitung oder Darstellung eines bestimmten Gerätetyps.</p><h3>Bilddarstellung – Grundlagen</h3><p><b>Hi-Cat:</b> Graustufen-/Konturendarstellung. <b>Hi-Mat:</b> Farbliche Materialhinweise. Die Zusammenfassung nennt Orange für organische, Blau für anorganische/metallische und Grün für Mischbereiche. Farben erlauben allein keine sichere Identifikation.</p><h3>Beispiele für Auswertefunktionen</h3><p>Negativ · Organic Only · Organic Stripping · Schwarz-Weiß · Konturenverstärkung · High · Vari. Verfügbarkeit, genaue Wirkung und Bedienung unterscheiden sich je nach Gerät und Software.</p><h3>Illustration für die Lern-App</h3><img class="gpa-learning-image" src="gpa-illustration.png" alt="Entwurfsillustration einer Gepäckprüfanlage und einer Lernoberfläche"><p class="muted">KI-generierte Entwurfsillustration; Beschriftungen und technische Details sind schematisch und nicht als verbindliche Geräteanweisung zu verwenden.</p></div>`;
 if(selected==='recht')body=`<div class="card"><h3>EU-Recht: Was gilt – und warum?</h3><p><b>VO (EG) 300/2008:</b> Legt die gemeinsamen Grundregeln für die Sicherheit der Zivilluftfahrt fest.</p><p><b>VO (EG) 272/2009:</b> Ergänzt die gemeinsamen Grundstandards.</p><p><b>DVO (EU) 2015/1998:</b> Enthält detaillierte Durchführungsmaßnahmen. Immer die geltende, geänderte Fassung beachten.</p><h3>Vier-Säulen-Modell – Lernübersicht</h3><p>Ein vereinfachtes Modell für die Aufgabenverteilung: <b>§ 5 LuftSiG</b> Luftsicherheitsbehörden, <b>§ 8</b> Flugplatzbetreiber, <b>§ 9</b> Luftfahrtunternehmen und <b>§ 9a</b> Beteiligte der sicheren Lieferkette. Das Modell ist eine Lernhilfe; maßgeblich sind die gesetzlichen Einzelregelungen.</p><p><b>Merke:</b> In allen Modulen sind nur die tatsächlich erforderlichen Kompetenzen und zulässigen Kontrollmethoden entscheidend.</p></div>`;
 if(selected==='begriffe')body=`<div class="card"><h3>Kontrolltechnik – verständlich erklärt</h3><p><b>GPA:</b> Gepäckprüfanlage (Röntgentechnik). <b>WTMD:</b> Metalldetektorschleuse. <b>HHMD:</b> Handmetalldetektor. <b>ETD:</b> Sprengstoffspurendetektion. <b>EDD:</b> Sprengstoffspürhunde. <b>EDS:</b> Sprengstoffdetektionssystem. <b>LEDS:</b> Flüssigsprengstoffdetektionssystem.</p><h3>Kontrollmethoden</h3><p>Je nach Aufgabe und Rechtsgrundlage kommen beispielsweise Sichtkontrolle, manuelle Kontrolle, Metalldetektion, Röntgenkontrolle, ETD, EDD oder zugelassene Scanner zum Einsatz. <b>Nicht jede Methode ist für jede Aufgabe zulässig.</b></p><h3>USBV und KSBV</h3><p><b>USBV:</b> Unkonventionelle Spreng- und Brandvorrichtung – eine improvisierte Vorrichtung. <b>KSBV:</b> Konventionelle Spreng- und Brandvorrichtung – Bezeichnung im jeweiligen Schulungskontext; die genaue Verwendung bitte mit dem Unterrichtsmaterial abgleichen.</p><p><b>Sicherheit:</b> Verdächtige Gegenstände nicht eigenmächtig bewegen, öffnen oder untersuchen. Abstand und vorgesehene Meldewege beachten. Keine technischen Bau- oder Erkennungsdetails in dieser Lernhilfe.</p><h3>Crew und Flughafenlieferungen</h3><p><b>Deadhead:</b> dienstlich mitreisendes Besatzungsmitglied ohne aktive Funktion auf dem Flug. Der Status allein befreit nicht automatisch von Sicherheitsmaßnahmen. <b>EASA Form 1:</b> technisches Freigabedokument, kein allgemeiner Luftsicherheitsnachweis.</p></div>`;
 if(selected==='quiz')body=`<div class="card"><h3>3 · Wissenstest</h3><p>Sechs selbst erstellte Verständnisfragen. Die Auswertung erfolgt hier separat; die Fragen im Hauptkatalog und deren Statistik bleiben unverändert.</p><div id="lessonQuiz">${LESSON_QUIZ.map((q,i)=>`<fieldset class="lesson-question"><legend>${i+1}. ${q.q}</legend>${q.a.map((v,j)=>`<label><input type="radio" name="lq${i}" value="${j}"> ${v}</label>`).join('')}<p id="lf${i}" class="muted"></p></fieldset>`).join('')}</div><button class="primary" onclick="gradeNewLessons()">AUSWERTEN</button><button class="lesson-restart" onclick="openNewLessons('quiz')">Neu beginnen</button><p id="lessonResult" role="status"></p></div>`;
 R(nav+note+body+'<footer>© 2026 Sven Willumeit – Alle Rechte vorbehalten</footer>');
}
function gradeNewLessons(){let score=0,answered=0;LESSON_QUIZ.forEach((q,i)=>{const el=document.querySelector(`input[name="lq${i}"]:checked`);const f=document.getElementById('lf'+i);if(!el){f.textContent='Bitte Antwort wählen.';return;}answered++;const good=Number(el.value)===q.c;if(good)score++;f.textContent=(good?'✓ Richtig. ':'✗ Nicht richtig. ')+q.why;});document.getElementById('lessonResult').textContent=`${score} von ${LESSON_QUIZ.length} richtig (${answered} beantwortet).`}

// Historische ECAC-Unterlagen (2009) sind kein Ersatz für aktuelle Geräteanweisungen.
